version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongo-calendar-db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-database:/data/db