
# Develop build and deploy
name: oooi-api
on:
  push:
    brances:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world | build"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world | deploy"
