# test
# Develop build and deploy

name: oooi-api-dev
on:
  push:
    brances:
      - development

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Copy repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - run: set -eu
      - run: mkdir $HOME/.ssh
      - run: echo "${{ secrets.DEV_PRIVATE_KEY }}" > "$HOME/.ssh/github_private_key"
      - run: chmod 600 "$HOME/.ssh/github_private_key"
      - run: cat $HOME/.ssh/github_private_key

      - run: npm install
      - run: npm run build


      - run: cd node_modules && rsync -e "ssh -i $HOME/.ssh/github_private_key -o StrictHostKeyChecking=no" --archive --compress --delete . github-user@206.189.12.4:/var/www/dev.oooi.app/node_modules/
      - run: cd dist && rsync -e "ssh -i $HOME/.ssh/github_private_key -o StrictHostKeyChecking=no" --archive --compress --delete . github-user@206.189.12.4:/var/www/dev.oooi.app/api/
      - run: ssh -i $HOME/.ssh/github_private_key -o StrictHostKeyChecking=no github-user@206.189.12.4 "sudo cp /var/www/dev.oooi.app/api/.env /var/www/dev.oooi.app/.tmp-env"
      - run: cd dist && rsync -e "ssh -i $HOME/.ssh/github_private_key -o StrictHostKeyChecking=no" --archive --compress --delete . github-user@206.189.12.4:/var/www/dev.oooi.app/api/
      - run: ssh -i $HOME/.ssh/github_private_key -o StrictHostKeyChecking=no github-user@206.189.12.4 "sudo mv /var/www/dev.oooi.app/.tmp-env /var/www/dev.oooi.app/api/.env"